name: Build Windows (reusable)

on:
  workflow_call:
    outputs:
      artifact-name:
        description: "Name of the uploaded Windows artifact"
        value: windows-build

jobs:
  build-windows:
    name: Build Windows
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build

      - name: Build Electron app (Windows)
        run: npm run dist:win -- --publish never

      - name: Upload Windows artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: |
            release/*.exe
            release/*.exe.blockmap
            release/latest.yml
