name: Build and Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build

      - name: Build and Publish Electron app
        run: npm run dist:win -- --publish always
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_RELEASE_BODY: |
            ## 🚀 DevUtils ${{ github.ref_name }}

            Download the version that suits your needs:

            ### 📦 Installer Version
            - **DevUtils Setup ${{ github.ref_name }}.exe** - Full installer with shortcuts and uninstaller

            ### 🎒 Portable Version  
            - **DevUtils-Portable-${{ github.ref_name }}.exe** - Portable version, no installation required

            ## 🔧 System Requirements
            - Windows 10 or later (64-bit)
            - No additional dependencies required

            ## 🆕 What's New
            See [CHANGELOG.md](https://github.com/ahammadabdullah/dev-utils/blob/main/CHANGELOG.md) for detailed changes.

      - name: Upload artifacts (optional backup)
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: |
            dist/*.exe
            dist/*.exe.blockmap
            dist/latest.yml
