name: Build and Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  build-and-release:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build

      - name: Build Electron app
        run: npm run dist:all -- --publish never

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: |
            release/*.exe
            release/*.exe.blockmap
            release/latest.yml
            release/*.dmg
            release/*.dmg.blockmap
            release/latest-mac.yml

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            release/*.exe
            release/*.exe.blockmap
            release/*.dmg
            release/*.dmg.blockmap
          draft: false
          prerelease: false
          generate_release_notes: true
          name: DevUtils ${{ github.ref_name }}
          body: |
            # 🚀 DevUtils ${{ github.ref_name }}

            Download the version that suits your needs:

            ## Windows Version
            - **DevUtils Setup ${{ github.ref_name }}.exe** - Full installer with shortcuts and uninstaller
            - **DevUtils-Portable-${{ github.ref_name }}.exe** - Portable version, no installation required
            
            ### 🔧 System Requirements
            - Windows 10 or later (64-bit)
            - No additional dependencies required

            ## MacOS Version
            - **DevUtils-${{ github.ref_name }}-arm64.dmg** - Disk image for easy installation on Apple Silicon
            - **DevUtils-${{ github.ref_name }}.dmg** - Disk image for easy installation on Intel Macs

            ### 🔧 System Requirements
            - macOS 13 or later (Apple Silicon / Intel)
            - No additional dependencies required

            ## 🆕 What's New
            See [CHANGELOG.md](https://github.com/ahammadabdullah/dev-utils/blob/main/CHANGELOG.md) for detailed changes.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
