name: Build and Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  # Use reusable workflow for Windows build
  build-windows:
    uses: ./.github/workflows/build-windows.yml

  # macOS build temporarily disabled. When ready, switch to the reusable workflow below.
  # build-macos:
  #   uses: ./.github/workflows/build-macos.yml

  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs:
      - build-windows
    steps:
      - name: Download Windows artifacts
        uses: actions/download-artifact@v4
        with:
          name: windows-build
          path: release

      # - name: Download macOS artifacts
      #   uses: actions/download-artifact@v4
      #   with:
      #     name: macos-build
      #     path: release

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            release/*.exe
            release/*.exe.blockmap
            release/latest.yml
          draft: false
          prerelease: false
          generate_release_notes: true
          name: DevUtils ${{ github.ref_name }}
          body: |
            # 🚀 DevUtils ${{ github.ref_name }}

            Download the version that suits your needs:

            ## Windows Version
            - **DevUtils Setup ${{ github.ref_name }}.exe** - Full installer with shortcuts and uninstaller
            - **DevUtils-Portable-${{ github.ref_name }}.exe** - Portable version, no installation required
            
            ### 🔧 System Requirements
            - Windows 10 or later (64-bit)
            - No additional dependencies required

            ## 🆕 What's New
            See [CHANGELOG.md](https://github.com/ahammadabdullah/dev-utils/blob/main/CHANGELOG.md) for detailed changes.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
